ufr.base.url=https://int.ufrulkint-api.moscow.alfaintra.net/ufr-eos-ul-ncins-core-api
ufr.relaxed-https-validation=true
ufr.a-user-id=123456
ufr.a-customer-id=123456
ufr.a-client-type=UL
ufr.a-channel-id=NIB